version: 2
jobs:
    build:
        docker:
            - image: jetcipher/circleci-dotnet-core:3.1
        steps:
            - checkout
            - run:
                name: Restore
                command: dotnet restore
                working_directory: MovieFolderFormatter