version: 2
jobs:
    build:
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk:3.1
        steps:
            - checkout
            - run:
                name: Restore
                command: dotnet restore
                working_directory: MovieFolderFormatter
            - run:
                name: Tests
                command: dotnet build
                working_directory: MovieFolderFormatter
                - run:
                    name: build
                    command: dotnet test
                    working_directory: MovieFolderFormatter